name: state_restoration_hook
description: A Flutter package that provides a hooks to manage state restoration.

publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

